# action.yml
name: 'Deck Card Game'
description: 'This project is for submission purpose'
runs:
  using: 'docker'
  image: 'Dockerfile'
    
    
name: deck-card-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
